---
title: "ST447CodeCheck"
author: "Andrin Gehrig"
date: "2023-12-01"
output: html_document
---

```{r}
library(readxl) # for reading xlsx data
library(dplyr) # common package for data processing 
library(zoo) # for the na.locf() function
library(boot) # use the boot lib to estimate CIs (section 3.1)
# path to the raw data
path <- "dvsa1203.xls"
# define which sheets to read from the original file
sheet_names <- excel_sheets(path = path)[-1]
# create an empty data frame to store the data in
uk_df_wide <- data.frame()
# loop over all the tables in the original file
for (i in 1:length(sheet_names)) {# read and store table i in sheet i.
  # cleaning by skipping empty rows and headers and defining NA strings
  df_i <- read_xls(path, sheet = sheet_names[i], skip = 7, 
    col_names = F, na = c("",".."))
  # only select non-empty columns 
  df_i_relevant_cols <- df_i %>% select_if(~sum(!is.na(.)) > 0)
  # assign appropriate column names
  colnames(df_i_relevant_cols) <- c("Location", "Age",
                     "M_conducted","M_passes","M_pass_rate",
                     "F_conducted","F_passes","F_pass_rate",
                     "T_conducted","T_passes","T_pass_rate")
  # fill in some empty cells and remove unnecessary rows
  # set the correct data format for columns
  df_i_clean <- df_i_relevant_cols %>%
    mutate(Location = na.locf(Location) ) %>%
    filter(!is.na(Age) & Age != "Total") %>%
    mutate(Date = sheet_names[i]) %>%
    mutate(Date = as.factor(Date)) %>%
    mutate(Location = as.factor(Location)) %>%
    mutate(Age = as.factor(Age)) %>%
    select(Date, everything())  
  # append the data for sheet i to the data frame
  uk_df_wide <- rbind(uk_df_wide, df_i_clean)}
# reformat df for data analysis by creating a column for gender
uk_m_df <- uk_df_wide %>% # select male results
  rename(Passrate = M_pass_rate, Conducted = M_conducted) %>%
  select( -F_conducted, -F_passes, -F_pass_rate,
          -T_conducted, -T_passes, -T_pass_rate, -M_passes) %>%
  mutate(Gender = "M")
uk_f_df <- uk_df_wide %>% # select female results
  rename(Passrate = F_pass_rate, Conducted = F_conducted) %>%
  select( -F_passes, -T_conducted, -T_passes, -T_pass_rate,
          -M_conducted, -M_passes, -M_pass_rate) %>%
  mutate(Gender = "F")
# stack the df for male and female to get the full data again
uk_df <- rbind(uk_m_df, uk_f_df)
uk_df <- uk_df %>%
  arrange(Location, Date, Age) %>%
  mutate(Location = ifelse(Location == "Wood Green", 
  "Wood Green (London)", as.character(Location))) # Fix naming change


```


```{r}

# create a new data frames for the locations of interest
# create a numeric "Year" variable from the "Date"
# select only variables needed for the model estimation
relevant_locations <- uk_df %>%
  filter(Location=="Wood Green (London)" | Location=="Worthing" ) %>%
  mutate(Year = as.numeric(paste("20",substr(Date,6,7), sep = ""))) %>%
  select(Year, Age, Passrate, Gender, Location, Conducted) %>%
  mutate(Passrate = Passrate/100 ) # scale Passrate
# estimate a logistic model by creating a binary dependent variable
gl_mod = glm(cbind(Passrate*Conducted,Conducted-Passrate*Conducted)~., 
             family=binomial(logit), data = relevant_locations)
summary(gl_mod) # show the model output

```

```{r}
set.seed(8) # set a seed for reproducibility
# Create new df with the profile of XYZ for both locations
XYZ_profile <- data.frame(Year = 2024, Age = as.factor(19),
  Gender = "F",Location = c("Wood Green (London)","Worthing"))
gl_predictions <- c() # vector to store results (pred,ci_lb,ci_ub)
for (i in 1:2) { # fit and predict for worthing, wood green
  gl_boot_pred <- function(data, samp) {#def logit function for boot()
    gl_m<-glm(cbind(Passrate*Conducted,Conducted-Passrate*Conducted)~., 
            family=binomial(logit), data = relevant_locations[samp,])
    predict(gl_m, newdata = XYZ_profile[i,], type = "response")}
  # use the boot() function to implement the algorithm directly
  boot_results <- boot(data = relevant_locations, 
            statistic = gl_boot_pred, R = 1000)
  # use boot.ci to estimate a CI for the boot results above          
  boot_ci <- boot.ci(boot_results, conf = 0.95, type = "basic")
  gl_predictions <- c(gl_predictions,boot_results$statistic(),
            boot_ci$basic[4:5])}# store the two rows in matrix
gl_pred_results <- matrix(gl_predictions, nrow = 2, byrow = T)



```

```{r}

# Function to calculate t-tests (Welch two-sample)
significant_mean_diff <- function(passrate, conducted) {
  n1 <- conducted[1]
  n2 <- conducted[2]
  mean_x <- passrate[1]/100
  mean_y <- passrate[2]/100
  var_x <- (mean_x*(1-mean_x)) / n1
  var_y <- (mean_y*(1-mean_y)) / n2
  df <- ((var_x / n1 + var_y / n2)^2) / # degrees of freedom
    ((var_x^2) / (n1^2 * (n1 - 1)) + (var_y^2) / (n2^2 * (n2 - 1)))
  t_stat <- (mean_x - mean_y) / sqrt((var_x / n1) + (var_y / n2))
  p_value <- 1 - pt(t_stat, df) # p-value
  return(p_value<0.01)}
# select relevant data and compute significance of mean difference
binom_data <- uk_df %>%
  filter(Location=="Wood Green (London)" | Location=="Worthing" ) %>%
  mutate(Year = as.numeric(paste("20",substr(Date,6,7), sep = ""))) %>%
  filter(Year <= 2018) %>% select(-Date) %>%
  arrange(Age,Year, Gender, desc(Location) ) %>%
  group_by(Age,Year, Gender) %>%
  mutate(SignificantMeanDiff=significant_mean_diff(Passrate,Conducted))
# evaluate results for XYZs profile in Worthing
sup_worthing_xyz <- binom_data %>%
  filter(Location == "Worthing", Age == "19", Gender == "F",
         SignificantMeanDiff==T)

```

```{r}

worthing_data <- binom_data %>% #select Worthing
    filter(Location=="Worthing" )  %>%
    select(SignificantMeanDiff,Age,Gender,Year)
# Fit a logistic model to classify significance of the difference
gl_mod <- glm(SignificantMeanDiff ~ Age + Gender + Year, 
    data = worthing_data, family = binomial)
# Create new df with the profile of XYZ for the logistic model
xyz_worthing_2024 <- data.frame(Year = 2024, Age = as.factor(19), 
    Gender = "F")
# Predicted prob of the PR being significantly higher in Worthing
pred_worthing <- predict(gl_mod, 
    newdata = xyz_worthing_2024, type= "response")
cat(pred_worthing)
```

